import { IVendor } from '../../app/interfaces/vendor.interface';

export const Vendors: IVendor[] = [
  {
    src: 'logos/elite.png',
    name: 'Elite Diving Excursions Belize',
    description: 'Scuba diving tours in Belize',
    website: 'https://www.eliteadventuresbelize.com/',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '5012263483',
    email: 'info@eliteadventuresbelize.com',
    category: ['Diving', 'Fishing', 'Snorkelling'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/secret-beach.png',
    name: 'Secret Beach Waterpark bar & Grill',
    description: 'An Adventure in Paradise',
    website: 'https://www.secretbeachwaterpark.com/',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '',
    email: '',
    category: ['Restaurant', 'Bar', 'Wedding Venue'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/twisted-palm-villas.png',
    name: 'Twisted Palm Villas',
    description: 'Enjoy a Beach Side Resort in Belize',
    website: 'https://twistedpalmvillas.com/',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '',
    email: '',
    category: ['Hotel', 'Wedding Venue'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/island-dream-tours.png',
    name: 'Island Dream Tours',
    description:
      'Vacation Like You Never Have Before Because... " You Only Live Once"',
    website: 'https://www.islanddreamtours.com/',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '5016159656',
    email: 'info@islanddreamtours.com',
    category: ['Tours'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/playa-del-sala.png',
    name: 'Playa De Sala',
    description:
      'Experience a romantic escape at Playa De Sala, Belize&#rsquo;s exclusive adults-only boutique hotel.',
    website: 'https://twistedpalmvillas.com/',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '5016140650',
    email: 'info@playadesala.com',
    category: ['Hotel', 'Bar', 'Restaurant', 'Wedding Venue'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/the-truck-stop.png',
    name: 'Twisted Palm Villas',
    description:
      'San Pedro&#rsquo;s Entertainment Destination and 1st & Only Beer Garden',
    website: 'https://truckstopbz.com/ ',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '5012263663',
    email: 'info@truckstopbz.com',
    category: ['Restaurant', 'Bar', 'Wedding Venue'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/moon-bar.png',
    name: 'Moon Bar',
    description:
      'an exclusive, adults-only (18+) beachside bar and pizzeria with a relaxed and inviting atmosphere',
    website: 'https://mangatavillas.com/moon-bar',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: '5016108953',
    email: '',
    category: ['Restaurant', 'Bar', 'Wedding Venue'],
    comments: '',
    status: 'Active',
    tags: [],
  },
  {
    src: 'logos/terrazas.png',
    name: 'Las Terrazas Belize Resort',
    description: 'Luxury Boutique Resort in Ambergris Caye',
    website: 'https://lasterrazasresort.com',
    address: '',
    city: 'San Pedro, Ambergris Caye',
    phone: [{ us: '7137801233' }, { us: '8004471553' }],
    email: '',
    category: '',
    comments: '',
    status: 'Active',
    tags: [],
  },
];
