import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root',
})
export class TagService {
  private baseAPIUrl: string = environment.baseAPIUrl;
  private API = `${environment.API}/tags`;
  private tagsAPI = `${this.baseAPIUrl}${this.API}`;

  constructor(private http: HttpClient) {}
  getTags(): Observable<any> {
    return this.http.get(`${this.tagsAPI}/get-tags`);
  }

  getTag(id: string): Observable<any> {
    return this.http.get(`${this.tagsAPI}/get-tag/${id}`);
  }
  getCountries() {
    return of([
      { name: 'Afghanistan', id: '1', freq: '5', code: 'AF' },
      { name: 'Åland Islands', id: '2', freq: '5', code: 'AX' },
      { name: 'Albania', id: '3', freq: '5', code: 'AL' },
      { name: 'Algeria', id: '4', freq: '5', code: 'DZ' },
      { name: 'American Samoa', id: '5', freq: '5', code: 'AS' },
      { name: 'Andorra', id: '6', freq: '5', code: 'AD' },
      { name: 'Angola', id: '7', freq: '5', code: 'AO' },
      { name: 'Anguilla', id: '8', freq: '5', code: 'AI' },
      { name: 'Antarctica', id: '9', freq: '5', code: 'AQ' },
      { name: 'Antigua and Barbuda', id: '10', freq: '5', code: 'AG' },
      { name: 'Argentina', id: '11', freq: '5', code: 'AR' },
      { name: 'Armenia', id: '12', freq: '5', code: 'AM' },
      { name: 'Aruba', id: '13', freq: '5', code: 'AW' },
      { name: 'Australia', id: '14', freq: '5', code: 'AU' },
      { name: 'Austria', id: '15', freq: '5', code: 'AT' },
      { name: 'Azerbaijan', id: '16', freq: '5', code: 'AZ' },
      { name: 'Bahamas', id: '17', freq: '5', code: 'BS' },
      { name: 'Bahrain', id: '18', freq: '5', code: 'BH' },
      { name: 'Bangladesh', id: '19', freq: '5', code: 'BD' },
      { name: 'Barbados', id: '20', freq: '5', code: 'BB' },
      { name: 'Belarus', id: '21', freq: '5', code: 'BY' },
      { name: 'Belgium', id: '22', freq: '5', code: 'BE' },
      { name: 'Belize', id: '23', freq: '5', code: 'BZ' },
      { name: 'Benin', id: '24', freq: '5', code: 'BJ' },
      { name: 'Bermuda', id: '25', freq: '5', code: 'BM' },
      { name: 'Bhutan', id: '26', freq: '5', code: 'BT' },
      { name: 'Bolivia', id: '27', freq: '5', code: 'BO' },
      { name: 'Bosnia and Herzegovina', id: '28', freq: '5', code: 'BA' },
      { name: 'Botswana', id: '29', freq: '5', code: 'BW' },
      { name: 'Bouvet Island', id: '30', freq: '5', code: 'BV' },
      { name: 'Brazil', id: '31', freq: '5', code: 'BR' },
      {
        name: 'British Indian Ocean Territory',
        id: '32',
        freq: '5',
        code: 'IO',
      },
      { name: 'Brunei Darussalam', id: '33', freq: '5', code: 'BN' },
      { name: 'Bulgaria', id: '34', freq: '5', code: 'BG' },
      { name: 'Burkina Faso', id: '35', freq: '5', code: 'BF' },
      { name: 'Burundi', id: '36', freq: '5', code: 'BI' },
      { name: 'Cambodia', id: '37', freq: '5', code: 'KH' },
      { name: 'Cameroon', id: '38', freq: '5', code: 'CM' },
      { name: 'Canada', id: '39', freq: '5', code: 'CA' },
      { name: 'Cape Verde', id: '40', freq: '5', code: 'CV' },
      { name: 'Cayman Islands', id: '41', freq: '5', code: 'KY' },
      { name: 'Central African Republic', id: '42', freq: '5', code: 'CF' },
      { name: 'Chad', id: '43', freq: '5', code: 'TD' },
      { name: 'Chile', id: '44', freq: '5', code: 'CL' },
      { name: 'China', id: '45', freq: '5', code: 'CN' },
      { name: 'Christmas Island', id: '46', freq: '5', code: 'CX' },
      { name: 'Cocos (Keeling) Islands', id: '47', freq: '5', code: 'CC' },
      { name: 'Colombia', id: '48', freq: '5', code: 'CO' },
      { name: 'Comoros', id: '49', freq: '5', code: 'KM' },
      { name: 'Congo', id: '50', freq: '5', code: 'CG' },
      {
        name: 'Congo, The Democratic Republic of the',
        id: '51',
        freq: '5',
        code: 'CD',
      },
      { name: 'Cook Islands', id: '52', freq: '5', code: 'CK' },
      { name: 'Costa Rica', id: '53', freq: '5', code: 'CR' },
      { name: 'Cote D"Ivoire', id: '54', freq: '5', code: 'CI' },
      { name: 'Croatia', id: '55', freq: '5', code: 'HR' },
      { name: 'Cuba', id: '56', freq: '5', code: 'CU' },
      { name: 'Cyprus', id: '57', freq: '5', code: 'CY' },
      { name: 'Czech Republic', id: '58', freq: '5', code: 'CZ' },
      { name: 'Denmark', id: '59', freq: '5', code: 'DK' },
      { name: 'Djibouti', id: '60', freq: '5', code: 'DJ' },
      { name: 'Dominica', id: '61', freq: '5', code: 'DM' },
      { name: 'Dominican Republic', id: '62', freq: '5', code: 'DO' },
      { name: 'Ecuador', id: '63', freq: '5', code: 'EC' },
      { name: 'Egypt', id: '64', freq: '5', code: 'EG' },
      { name: 'El Salvador', id: '65', freq: '5', code: 'SV' },
      { name: 'Equatorial Guinea', id: '66', freq: '5', code: 'GQ' },
      { name: 'Eritrea', id: '67', freq: '5', code: 'ER' },
      { name: 'Estonia', id: '68', freq: '5', code: 'EE' },
      { name: 'Ethiopia', id: '69', freq: '5', code: 'ET' },
      { name: 'Falkland Islands (Malvinas)', id: '70', freq: '5', code: 'FK' },
      { name: 'Faroe Islands', id: '71', freq: '5', code: 'FO' },
      { name: 'Fiji', id: '72', freq: '5', code: 'FJ' },
      { name: 'Finland', id: '73', freq: '5', code: 'FI' },
      { name: 'France', id: '74', freq: '5', code: 'FR' },
      { name: 'French Guiana', id: '75', freq: '5', code: 'GF' },
      { name: 'French Polynesia', id: '76', freq: '5', code: 'PF' },
      { name: 'French Southern Territories', id: '77', freq: '5', code: 'TF' },
      { name: 'Gbon', id: '77', freq: '78', code: 'GA' },
      { name: 'Gambia', id: '78', freq: '79', code: 'GM' },
      { name: 'Georgia', id: '79', freq: '80', code: 'GE' },
      { name: 'Germany', id: '80', freq: '81', code: 'DE' },
      { name: 'Ghana', id: '81', freq: '82', code: 'GH' },
      { name: 'Gibraltar', id: '82', freq: '5', code: 'GI' },
      { name: 'Greece', id: '83', freq: '5', code: 'GR' },
      { name: 'Greenland', id: '84', freq: '5', code: 'GL' },
      { name: 'Grenada', id: '85', freq: '5', code: 'GD' },
      { name: 'Guadeloupe', id: '86', freq: '5', code: 'GP' },
      { name: 'Guam', id: '87', freq: '5', code: 'GU' },
      { name: 'Guatemala', id: '88', freq: '5', code: 'GT' },
      { name: 'Guernsey', id: '89', freq: '5', code: 'GG' },
      { name: 'Guinea', id: '90', freq: '5', code: 'GN' },
      { name: 'Guinea-Bissau', id: '91', freq: '5', code: 'GW' },
      { name: 'Haiti', id: '1', freq: '5', code: 'HT' },
      {
        name: 'Heard Island and Mcdonald Islands',
        id: '1',
        freq: '5',
        code: 'HM',
      },
      { name: 'Holy See (Vatican City State)', id: '1', freq: '5', code: 'VA' },
      { name: 'Honduras', id: '1', freq: '5', code: 'HN' },
      { name: 'Hong Kong', id: '1', freq: '5', code: 'HK' },
      { name: 'Hungary', id: '1', freq: '5', code: 'HU' },
      { name: 'Iceland', id: '1', freq: '5', code: 'IS' },
      { name: 'India', id: '1', freq: '5', code: 'IN' },
      { name: 'Indonesia', id: '1', freq: '5', code: 'ID' },
      { name: 'Iran, Islamic Republic Of', id: '1', freq: '5', code: 'IR' },
      { name: 'Iraq', id: '1', freq: '5', code: 'IQ' },
      { name: 'Ireland', id: '1', freq: '5', code: 'IE' },
      { name: 'Isle of Man', id: '1', freq: '5', code: 'IM' },
      { name: 'Israel', id: '1', freq: '5', code: 'IL' },
      { name: 'Italy', id: '1', freq: '5', code: 'IT' },
      { name: 'Jamaica', id: '1', freq: '5', code: 'JM' },
      { name: 'Japan', id: '1', freq: '5', code: 'JP' },
      { name: 'Jersey', id: '1', freq: '5', code: 'JE' },
      { name: 'Jordan', id: '1', freq: '5', code: 'JO' },
      { name: 'Kazakhstan', id: '1', freq: '5', code: 'KZ' },
      { name: 'Kenya', id: '1', freq: '5', code: 'KE' },
      { name: 'Kiribati', id: '1', freq: '5', code: 'KI' },
      {
        name: 'Korea, Democratic People"S Republic of',
        id: '1',
        freq: '5',
        code: 'KP',
      },
      { name: 'Korea, Republic of', id: '1', freq: '5', code: 'KR' },
      { name: 'Kuwait', id: '1', freq: '5', code: 'KW' },
      { name: 'Kyrgyzstan', id: '1', freq: '5', code: 'KG' },
      {
        name: 'Lao People"S Democratic Republic',
        id: '1',
        freq: '5',
        code: 'LA',
      },
      { name: 'Latvia', id: '1', freq: '5', code: 'LV' },
      { name: 'Lebanon', id: '1', freq: '5', code: 'LB' },
      { name: 'Lesotho', id: '1', freq: '5', code: 'LS' },
      { name: 'Liberia', id: '1', freq: '5', code: 'LR' },
      { name: 'Libyan Arab Jamahiriya', id: '1', freq: '5', code: 'LY' },
      { name: 'Liechtenstein', id: '1', freq: '5', code: 'LI' },
      { name: 'Lithuania', id: '1', freq: '5', code: 'LT' },
      { name: 'Luxembourg', id: '1', freq: '5', code: 'LU' },
      { name: 'Macao', id: '1', freq: '5', code: 'MO' },
      {
        name: 'Macedonia, The Former Yugoslav Republic of',
        id: '1',
        freq: '5',
        code: 'MK',
      },
      { name: 'Madagascar', id: '1', freq: '5', code: 'MG' },
      { name: 'Malawi', id: '1', freq: '5', code: 'MW' },
      { name: 'Malaysia', id: '1', freq: '5', code: 'MY' },
      { name: 'Maldives', id: '1', freq: '5', code: 'MV' },
      { name: 'Mali', id: '1', freq: '5', code: 'ML' },
      { name: 'Malta', id: '1', freq: '5', code: 'MT' },
      { name: 'Marshall Islands', id: '1', freq: '5', code: 'MH' },
      { name: 'Martinique', id: '1', freq: '5', code: 'MQ' },
      { name: 'Mauritania', id: '1', freq: '5', code: 'MR' },
      { name: 'Mauritius', id: '1', freq: '5', code: 'MU' },
      { name: 'Mayotte', id: '1', freq: '5', code: 'YT' },
      { name: 'Mexico', id: '1', freq: '5', code: 'MX' },
      {
        name: 'Micronesia, Federated States of',
        id: '1',
        freq: '5',
        code: 'FM',
      },
      { name: 'Moldova, Republic of', id: '1', freq: '5', code: 'MD' },
      { name: 'Monaco', id: '1', freq: '5', code: 'MC' },
      { name: 'Mongolia', id: '1', freq: '5', code: 'MN' },
      { name: 'Montserrat', id: '1', freq: '5', code: 'MS' },
      { name: 'Morocco', id: '1', freq: '5', code: 'MA' },
      { name: 'Mozambique', id: '1', freq: '5', code: 'MZ' },
      { name: 'Myanmar', id: '1', freq: '5', code: 'MM' },
      { name: 'Namibia', id: '1', freq: '5', code: 'NA' },
      { name: 'Nauru', id: '1', freq: '5', code: 'NR' },
      { name: 'Nepal', id: '1', freq: '5', code: 'NP' },
      { name: 'Netherlands', id: '1', freq: '5', code: 'NL' },
      { name: 'Netherlands Antilles', id: '1', freq: '5', code: 'AN' },
      { name: 'New Caledonia', id: '1', freq: '5', code: 'NC' },
      { name: 'New Zealand', id: '1', freq: '5', code: 'NZ' },
      { name: 'Nicaragua', id: '1', freq: '5', code: 'NI' },
      { name: 'Niger', id: '1', freq: '5', code: 'NE' },
      { name: 'Nigeria', id: '1', freq: '5', code: 'NG' },
      { name: 'Niue', id: '1', freq: '5', code: 'NU' },
      { name: 'Norfolk Island', id: '1', freq: '5', code: 'NF' },
      { name: 'Northern Mariana Islands', id: '1', freq: '5', code: 'MP' },
      { name: 'Norway', id: '1', freq: '5', code: 'NO' },
      { name: 'Oman', id: '1', freq: '5', code: 'OM' },
      { name: 'Pakistan', id: '1', freq: '5', code: 'PK' },
      { name: 'Palau', id: '1', freq: '5', code: 'PW' },
      {
        name: 'Palestinian Territory, Occupied',
        id: '1',
        freq: '5',
        code: 'PS',
      },
      { name: 'Panama', id: '1', freq: '5', code: 'PA' },
      { name: 'Papua New Guinea', id: '1', freq: '5', code: 'PG' },
      { name: 'Paraguay', id: '1', freq: '5', code: 'PY' },
      { name: 'Peru', id: '1', freq: '5', code: 'PE' },
      { name: 'Philippines', id: '1', freq: '5', code: 'PH' },
      { name: 'Pitcairn', id: '1', freq: '5', code: 'PN' },
      { name: 'Poland', id: '1', freq: '5', code: 'PL' },
      { name: 'Portugal', id: '1', freq: '5', code: 'PT' },
      { name: 'Puerto Rico', id: '1', freq: '5', code: 'PR' },
      { name: 'Qatar', id: '1', freq: '5', code: 'QA' },
      { name: 'Reunion', id: '1', freq: '5', code: 'RE' },
      { name: 'Romania', id: '1', freq: '5', code: 'RO' },
      { name: 'Russian Federation', id: '1', freq: '5', code: 'RU' },
      { name: 'RWANDA', id: '1', freq: '5', code: 'RW' },
      { name: 'Saint Helena', id: '1', freq: '5', code: 'SH' },
      { name: 'Saint Kitts and Nevis', id: '1', freq: '5', code: 'KN' },
      { name: 'Saint Lucia', id: '1', freq: '5', code: 'LC' },
      { name: 'Saint Pierre and Miquelon', id: '1', freq: '5', code: 'PM' },
      {
        name: 'Saint Vincent and the Grenadines',
        id: '1',
        freq: '5',
        code: 'VC',
      },
      { name: 'Samoa', id: '1', freq: '5', code: 'WS' },
      { name: 'San Marino', id: '1', freq: '5', code: 'SM' },
      { name: 'Sao Tome and Principe', id: '1', freq: '5', code: 'ST' },
      { name: 'Saudi Arabia', id: '1', freq: '5', code: 'SA' },
      { name: 'Senegal', id: '1', freq: '5', code: 'SN' },
      { name: 'Serbia and Montenegro', id: '1', freq: '5', code: 'CS' },
      { name: 'Seychelles', id: '1', freq: '5', code: 'SC' },
      { name: 'Sierra Leone', id: '1', freq: '5', code: 'SL' },
      { name: 'Singapore', id: '1', freq: '5', code: 'SG' },
      { name: 'Slovakia', id: '1', freq: '5', code: 'SK' },
      { name: 'Slovenia', id: '1', freq: '5', code: 'SI' },
      { name: 'Solomon Islands', id: '1', freq: '5', code: 'SB' },
      { name: 'Somalia', id: '1', freq: '5', code: 'SO' },
      { name: 'South Africa', id: '1', freq: '5', code: 'ZA' },
      {
        name: 'South Georgia and the South Sandwich Islands',
        code: 'GS',
      },
      { name: 'Spain', id: '1', freq: '5', code: 'ES' },
      { name: 'Sri Lanka', id: '1', freq: '5', code: 'LK' },
      { name: 'Sudan', id: '1', freq: '5', code: 'SD' },
      { name: 'Suriname', id: '1', freq: '5', code: 'SR' },
      { name: 'Svalbard and Jan Mayen', id: '1', freq: '5', code: 'SJ' },
      { name: 'Swaziland', id: '1', freq: '5', code: 'SZ' },
      { name: 'Sweden', id: '1', freq: '5', code: 'SE' },
      { name: 'Switzerland', id: '1', freq: '5', code: 'CH' },
      { name: 'Syrian Arab Republic', id: '1', freq: '5', code: 'SY' },
      { name: 'Taiwan, Republic of China', id: '1', freq: '5', code: 'TW' },
      { name: 'Tajikistan', id: '1', freq: '5', code: 'TJ' },
      { name: 'Tanzania, United Republic of', id: '1', freq: '5', code: 'TZ' },
      { name: 'Thailand', id: '1', freq: '5', code: 'TH' },
      { name: 'Timor-Leste', id: '1', freq: '5', code: 'TL' },
      { name: 'Togo', id: '1', freq: '5', code: 'TG' },
      { name: 'Tokelau', id: '1', freq: '5', code: 'TK' },
      { name: 'Tonga', id: '1', freq: '5', code: 'TO' },
      { name: 'Trinidad and Tobago', id: '1', freq: '5', code: 'TT' },
      { name: 'Tunisia', id: '1', freq: '5', code: 'TN' },
      { name: 'Turkey', id: '1', freq: '5', code: 'TR' },
      { name: 'Turkmenistan', id: '1', freq: '5', code: 'TM' },
      { name: 'Turks and Caicos Islands', id: '1', freq: '5', code: 'TC' },
      { name: 'Tuvalu', id: '1', freq: '5', code: 'TV' },
      { name: 'Uganda', id: '1', freq: '5', code: 'UG' },
      { name: 'Ukraine', id: '1', freq: '5', code: 'UA' },
      { name: 'United Arab Emirates', id: '1', freq: '5', code: 'AE' },
      { name: 'United Kingdom', id: '1', freq: '5', code: 'GB' },
      { name: 'United States', id: '1', freq: '5', code: 'US' },
      {
        name: 'United States Minor Outlying Islands',
        id: '1',
        freq: '5',
        code: 'UM',
      },
      { name: 'Uruguay', id: '1', freq: '5', code: 'UY' },
      { name: 'Uzbekistan', id: '1', freq: '5', code: 'UZ' },
      { name: 'Vanuatu', id: '1', freq: '5', code: 'VU' },
      { name: 'Venezuela', id: '1', freq: '5', code: 'VE' },
      { name: 'Viet Nam', id: '1', freq: '5', code: 'VN' },
      { name: 'Virgin Islands, British', id: '1', freq: '5', code: 'VG' },
      { name: 'Virgin Islands, U.S.', id: '1', freq: '5', code: 'VI' },
      { name: 'Wallis and Futuna', id: '1', freq: '5', code: 'WF' },
      { name: 'Western Sahara', id: '1', freq: '5', code: 'EH' },
      { name: 'Yemen', id: '1', freq: '5', code: 'YE' },
      { name: 'Zambia', id: '1', freq: '5', code: 'ZM' },
      { name: 'Zimbabwe', id: '1', freq: '5', code: 'ZW' },
    ]);
  }
}
